wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: huggingface
    huggingface_version: 4.21.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val/loss
      5: 1
      6:
      - 1
    - 1: test/loss
      5: 1
      6:
      - 1
    python_version: 3.8.13
    start_time: 1661804084.202668
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.8.13
      5: 0.13.2
      6: 4.21.2
      8:
      - 2
      - 5
